#!/bin/bash

# Install bashrc
ln -nsf ~/dotfiles/shell/.bashrc ~/.bash_profile

# Install vim
ln -nsf ~/dotfiles/vim/.vimrc ~/.vimrc
#rm -rf .vim
#git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
# Still need a way to call vundle from this script and then compile
# YouCompleteMe

# Install sublime
ln -nsf /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl /usr/local/bin/subl
ln -nsf ~/dotfiles/sublime/* ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User

chsh -s /bin/zsh
