#!/bin/bash
rm -f ~/.vimrc
ln -s ~/dotfiles/vim/.vimrc ~/.vimrc

rm -f ~/.bash_profile
ln -s ~/dotfiles/shell/.bashrc ~/.bash_profile

# Add sublime to /usr/local/bin
ln -s /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl /usr/local/bin/subl
